### ISSUE TITLE
Cannot read property 'Statement' of undefined

### ISSUE THREAD

**Issue by yaohaizh** [Microsoft/vscode-languageserver-node#470]
Use the "5.3.0-next.2" for try out the semantic selection. The response is below, but received the above error for the following response: 

```json
[Trace - 11:13:28 PM] Received response 'textDocument/selectionRange - (6)' in 352ms.
Result: [
    [
        {
            "kind": "statement",
            "range": {
                "start": {
                    "line": 46,
                    "character": 20
                },
                "end": {
                    "line": 46,
                    "character": 22
                }
            }
        },
        {
            "kind": "statement",
            "range": {
                "start": {
                    "line": 46,
                    "character": 15
                },
                "end": {
                    "line": 46,
                    "character": 22
                }
            }
        },
        {
            "kind": "statement",
            "range": {
                "start": {
                    "line": 46,
                    "character": 15
                },
                "end": {
                    "line": 46,
                    "character": 30
                }
            }
        },
        {
            "kind": "statement",
            "range": {
                "start": {
                    "line": 46,
                    "character": 8
                },
                "end": {
                    "line": 46,
                    "character": 31
                }
            }
        },
        {
            "kind": "statement",
            "range": {
                "start": {
                    "line": 45,
                    "character": 27
                },
                "end": {
                    "line": 47,
                    "character": 5
                }
            }
        },
        {
            "kind": "statement",
            "range": {
                "start": {
                    "line": 45,
                    "character": 4
                },
                "end": {
                    "line": 47,
                    "character": 5
                }
            }
        },
        {
            "kind": "statement",
            "range": {
                "start": {
                    "line": 24,
                    "character": 0
                },
                "end": {
                    "line": 49,
                    "character": 1
                }
            }
        },
        {
            "kind": "statement",
            "range": {
                "start": {
                    "line": 0,
                    "character": 0
                },
                "end": {
                    "line": 50,
                    "character": 0
                }
            }
        }
    ]
]
```
Error source: 
```js
    asSelectionRangeKind(kind) {
        switch (kind) {
            case vscode_languageserver_protocol_1.SelectionRangeKind.Empty:
                return vscode_1.SelectionRangeKind.Empty;
            case vscode_languageserver_protocol_1.SelectionRangeKind.Statement:
                return vscode_1.SelectionRangeKind.Statement;
            case vscode_languageserver_protocol_1.SelectionRangeKind.Declaration:
                return vscode_1.SelectionRangeKind.Declaration;
            default:
                return vscode_1.SelectionRangeKind.Empty;
        }
    }
```

**Comment by Gama11** [comment]
Might be the same issue as #468?

**Comment by dbaeumer** [comment]
@yaohaizh since the semantic selection is proposed API you need to enable proposed API in our `package.json` as well. See https://code.visualstudio.com/api/advanced-topics/using-proposed-api

Please note that extensions using proposed API can't be published to the market place since they will not run on stable releases.

Let me know if this helps.

**Comment by dbaeumer** [comment]
I published new version with a correct types dependency. However since sememantic selection has no interface in types yet I still thing this is not a dup.

**Comment by yaohaizh** [comment]
@dbaeumer I did enable the proposed API as the link said. Will try this later with the new types dependency.

**Comment by yaohaizh** [comment]
Still existing @dbaeumer The definition of SelectionRange on vscode.proposed.d.ts is different from the definition on this repo. And the SelectionRangeKind is not defined on the vscode.proposed.d.ts? Would this be a problem?

**Comment by dbaeumer** [comment]
@yaohaizh are you using insider? The propsoed API only works correctly with a stable release where the API still machtes.

**Comment by dbaeumer** [comment]
I will adopt the new API in vscode as soon as vscode ships a new stable release.

**Comment by yaohaizh** [comment]
@dbaeumer  Yes, I used the insider version for the semantic selection feature.

**Comment by dbaeumer** [comment]
OK. Then I will close the issue since there is nothing I can do about this. In LSP I only adopt stable version for provisional API.
